# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/khtml': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kbookmarks': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/karchive': '@stable'

Options:
    require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
