/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.khelpcenter.kcmhelpcenter.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "kcmhelpcenteradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KcmhelpcenterAdaptor
 */

KcmhelpcenterAdaptor::KcmhelpcenterAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KcmhelpcenterAdaptor::~KcmhelpcenterAdaptor()
{
    // destructor
}

void KcmhelpcenterAdaptor::slotIndexError(const QString &error)
{
    // handle method call org.kde.khelpcenter.kcmhelpcenter.slotIndexError
    QMetaObject::invokeMethod(parent(), "slotIndexError", Q_ARG(QString, error));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->slotIndexError(error);
}

void KcmhelpcenterAdaptor::slotIndexProgress()
{
    // handle method call org.kde.khelpcenter.kcmhelpcenter.slotIndexProgress
    QMetaObject::invokeMethod(parent(), "slotIndexProgress");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->slotIndexProgress();
}


#include "kcmhelpcenteradaptor.moc"
