#define WIS_DEFAULT_HIGHLIGHT_ENABLED	true
#define WIS_DEFAULT_HIGHLIGHT_NUMBER	1
#define WIS_DEFAULT_HIGHLIGHT_DELAY	2000
#define WIS_DEFAULT_EYES_ENABLED	true
#define WIS_DEFAULT_WARP_POINTER	1
#define HTML_DEFAULT_BG_COLOR		QColor( white )
#define HTML_DEFAULT_TXT_COLOR		QColor( black )
#define HTML_DEFAULT_LNK_COLOR		QColor( red )
#define HTML_DEFAULT_VLNK_COLOR		QColor( blue )
#define HTML_DEFAULT_CHANGE_CURSOR	true
#define HTML_DEFAULT_UNDERLINE_LINKS	true
#define HTML_DEFAULT_FORCE_DFLT_COLORS	true
